// ********** AUTH **********
export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const INITIAL = "INITIAL";
export const INITIALIZE_SESSION = "INITIALIZE_SESSION";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

// ********** PRODUCT **********
export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_CART_REQUEST = "GET_CART_REQUEST";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_PRODUCT_BY_ID_REQUEST = "GET_PRODUCT_BY_ID_REQUEST";
export const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS";
export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CHECK_OUT_REQUEST = "CHECK_OUT_REQUEST";
export const CHECK_OUT_SUCCESS = "CHECK_OUT_SUCCESS";
export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const PRODUCT_ERROR = "PRODUCT_ERROR";
export const CLEAR_PRODUCT_LIST = "CLEAR_PRODUCT_LIST";
export const CLEAR_PRODUCT = "CLEAR_PRODUCT";
export const CLEAR_CART_LIST = "CLEAR_CART_LIST";

// ********** DISCOUNT **********

export const GET_DISCOUNT_REQUEST = "GET_DISCOUNT_REQUEST";
export const GET_DISCOUNT_SUCCESS = "GET_DISCOUNT_SUCCESS";
export const CLEAR_DISCOUNT_LIST = "CLEAR_DISCOUNT_LIST";
export const DISCOUNT_ERROR = "DISCOUNT_ERROR";

// ********** PURCHASE **********

export const GET_PURCHASE_REQUEST = "GET_PURCHASE_REQUEST";
export const GET_PURCHASE_SUCCESS = "GET_PURCHASE_SUCCESS";
export const CLEAR_PURCHASE_LIST = "CLEAR_PURCHASE_LIST";
export const PURCHASE_ERROR = "PURCHASE_ERROR";

// ********** ERROR & MESSAGE **********
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const CLEAR_ERROR = "CLEAR_ERROR";
